// Canonical band-member roles shared by the API validator and frontend.
export const BAND_MEMBER_ROLES = Object.freeze({
  DRUMS: 'Drums',
  PERCUSSION: 'Percussion',
  BASS_GUITAR: 'Bass Guitar',
  RHYTHM_GUITAR: 'Rhythm Guitar',
  LEAD_GUITAR: 'Lead Guitar',
  KEYBOARDS: 'Keyboards',
  SYNTHESIZERS: 'Synthesizers',
  PIANO: 'Piano',
  ELECTRIC_ORGAN: 'Electric Organ',
  HAMMOND: 'Hammond',
  WURLITZER: 'Wurlitzer',
  ELECTRIC_PIANO: 'Electric Piano',
  LEAD_VOCALS: 'Lead Vocals',
  BACKGROUND_VOCALS: 'Background Vocals',
  TRUMPET: 'Trumpet',
  SAXOPHONE: 'Saxophone',
  TROMBONE: 'Trombone',
  FRENCH_HORN: 'French Horn',
  VIOLIN: 'Violin',
  FIDDLE: 'Fiddle',
  VIOLA: 'Viola',
  CELLO: 'Cello',
  PEDAL_STEEL: 'Pedal Steel',
  LAP_STEEL_GUITAR: 'Lap Steel Guitar',
  MANDOLIN: 'Mandolin',
  BANJO: 'Banjo',
  UKULELE: 'Ukulele',
  HARP: 'Harp',
  DJ: 'DJ',
  SAMPLER: 'Sampler',
  MULTI_INSTRUMENTALIST: 'Multi-Instrumentalist',
})

export const BAND_MEMBER_ROLE_OPTIONS = Object.freeze(Object.values(BAND_MEMBER_ROLES))
